# Generated by Django 2.1.7 on 2019-03-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoubleCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='doublecheck',
            name='fileid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.File'),
        ),
        migrations.AddField(
            model_name='doublecheck',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.CodeState'),
        ),
    ]
