# Generated by Django 2.1.7 on 2019-03-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='TramitFile',
        ),
    ]
