# Generated by Django 2.1.7 on 2019-03-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190316_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doublecheck',
            name='fileid',
        ),
        migrations.AddField(
            model_name='doublecheck',
            name='model_pic',
            field=models.ImageField(default='images/', upload_to='docs/'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
