# Generated by Django 2.1.7 on 2019-03-17 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190317_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('seller', models.ImageField(default='images/', upload_to='docs/')),
                ('buyer', models.ImageField(default='images/', upload_to='docs/')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.CodeState')),
            ],
        ),
        migrations.RemoveField(
            model_name='doublecheck',
            name='state',
        ),
        migrations.DeleteModel(
            name='DoubleCheck',
        ),
    ]
