# Generated by Django 2.1.7 on 2019-03-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190317_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesell',
            name='buyer',
            field=models.ImageField(default='images/', null=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='vehiclesell',
            name='seller',
            field=models.ImageField(default='images/', null=True, upload_to='docs/'),
        ),
    ]
