# Generated by Django 2.1.7 on 2019-03-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190317_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesell',
            name='buyer',
            field=models.ImageField(blank=True, default='images/', upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='vehiclesell',
            name='seller',
            field=models.ImageField(blank=True, default='images/', upload_to='docs/'),
        ),
    ]
