# Generated by Django 2.1.7 on 2019-03-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190317_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclesell',
            name='buyer_pic',
        ),
        migrations.RemoveField(
            model_name='vehiclesell',
            name='seller_pic',
        ),
        migrations.AddField(
            model_name='vehiclesell',
            name='buyer_cedula',
            field=models.ImageField(blank=True, default='images/', upload_to='docs/cedulas'),
        ),
        migrations.AddField(
            model_name='vehiclesell',
            name='buyer_propiedad',
            field=models.ImageField(blank=True, default='images/', upload_to='docs/propiedad'),
        ),
        migrations.AddField(
            model_name='vehiclesell',
            name='seller_cedula',
            field=models.ImageField(blank=True, default='images/', upload_to='docs/cedulas/'),
        ),
        migrations.AddField(
            model_name='vehiclesell',
            name='seller_propiedad',
            field=models.ImageField(blank=True, default='images/', upload_to='docs/propiedad/'),
        ),
    ]
